groups:
- name: DockerContainerAlerts
  rules:
  - alert: ContainerCPUHigh
    expr: rate(container_cpu_usage_seconds_total{name=~".+"}[5m]) * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Container CPU Usage High"
      description: "CPU usage for container {{ $labels.name }} is above 80% for 5 minutes."

  - alert: ContainerMemoryHigh
    expr: container_memory_usage_bytes{name=~".+"} / container_memory_limit_bytes{name=~".+"} * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Container Memory Usage High"
      description: "Memory usage for container {{ $labels.name }} is above 80% for 5 minutes."

  - alert: ContainerNotRunning
    expr: container_up == 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: "Container Not Running"
      description: "Container {{ $labels.name }} is not running."

  - alert: SonarQubeDown
    expr: up{job="sonarqube"} == 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: "SonarQube Instance Down"
      description: "The SonarQube instance is not reachable."

  - alert: DefectDojoDown
    expr: up{job="defectdojo"} == 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: "DefectDojo Instance Down"
      description: "The DefectDojo instance is not reachable."

  - alert: GrafanaDown
    expr: up{job="grafana"} == 0
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: "Grafana Instance Down"
      description: "The Grafana instance is not reachable."

  - alert: PrometheusDown
    expr: up{job="prometheus"} == 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: "Prometheus Instance Down"
      description: "The Prometheus instance is not reachable."
